version: "3"
services:
  database:
    container_name: schoolDB
    image: mysql
    ports:
      - "3316:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=schoolDB"